# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Resource settings for training pod
resources:
  requests:
    cpu: 19
    memory: 93604421089
  limits:
    cpu: 19
    memory: 93604421089

# Shorthands for setting both limits and requests of cpu/memory
cpu: null
memory: null

env:
  - name: OMP_NUM_THREADS
    value: "20"  # Set to the number of physical cores used by single worker
  - name: KMP_BLOCKTIME
    value: "0"  # 0 is a good default for most CNN models, could be adjusted for additional performance
  - name: KMP_AFFINITY
    value: "granularity=fine,verbose,compact,1,0"  # these are recommended affinity settings


# Settings for CLI automatic resource configuration
cpu_fraction: 0.5
memory_fraction: 0.5

# Settings below  are not intended to be changed
experimentName: {{ NAUTA.ExperimentName }} 
podCount: 1

TensorBoardPort: 8888
TensorIPythonPort: 6006

commandline:
  args:
    {% for arg in NAUTA.CommandLine %}
    - {{ arg }}
    {% endfor %}

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

service:
  type: ClusterIP